public class BB_C360_DataCloud_Resp_IB_v1 {
    // Leads Universe DMO
    public Decimal clientTurnover;        // Turnover_CY__c
    public Decimal cashFlowMovement;      // OVERDRAFT_MTD_AVE_VALUE__c
    public Decimal totalRevenue;          // NIR__c
    public Decimal lendingGrowth;         // Asset__c
    public String  vapm;                  // VAPM_YTD_CY__c
    // Profitabilitycsv DMO
    public Decimal profitBeforeTax;       // PBT__c
    public Decimal profitAfterTax;        // PAT__c
    public Decimal clientProfitability;   // PARCC__c
    public Decimal costToServe;           // COST__c
    public Decimal averageAdvances;       // AVERAGE_ADVANCES__c
    public Decimal averageDeposits;       // AVERAGE_DEPOSITS__c
    // NBPcsv DMO
    public String  marginTrend;           // VAPM_TREND__c
}
